### ISSUE TITLE
Why aren't these contributed back to Font-Awesome?

### ISSUE THREAD

**Issue by ketiko** [gregoryloucas/Fontstrap#46] opened 2013-02-07 17:59 UTC
What's the reason for maintaining a separate branch of additional icons?  It would be awesome if these were just included in the main Font-Awesome.

**Comment by wildchild** [comment] 2013-02-11 15:07
+1. @gregoryloucas, could you shed a light on this secret?

**Comment by mattes** [comment] 2013-02-14 01:31
+1

**Comment by rwojsznis** [comment] 2013-02-16 07:17
I lately discovered that there is more to Font-Awesome and I wonder just the same - why hide this? :+1:

**Comment by skatkov** [comment] 2013-03-15 21:36
would be good to see that in merged in Font-awesome

**Comment by digitalclutch** [comment] 2013-03-25 21:23
Perhaps they're concerned about any potential legal repercussions concerning fair use or quality issues that could arise from trademark holders in the future. Which would hinder it's widespread adoption, and ultimately prevent any potential inclusion in future versions of bootstrap.

Since bootstrap didn't include any trademarks in their glyphicons, I would have to assume that's by design, and must be a sticky situation when distributing software that will be used on a vast number of projects; in ways you can't anticipate. I assume the social icons included in the other repository followed company issued quality guidelines, and are so widely used there's no lingering questions regarding legal complications.

These are purely uneducated guesses. @gregoryloucas, @davegandy care to elaborate?

**Comment by gregoryloucas** [comment] 2013-04-02 15:36
Font Awesome 3.1.0 will have contributions.

**Closed as completed by gregoryloucas** 2013-04-02 15:36 UTC
